CREATE DATABASE IF NOT EXISTS Roperia;
USE Roperia;

DROP TABLE IF EXISTS Productos;
CREATE TABLE IF NOT EXISTS Productos(Id_Producto INT AUTO_INCREMENT PRIMARY KEY, Descripcion VARCHAR(20) NOT NULL,
 Precio FLOAT NOT NULL);

DROP TABLE IF EXISTS Ventas;
CREATE TABLE IF NOT EXISTS Ventas(Id_Venta INT NOT NULL, Producto_Id INT NOT NULL,
FOREIGN KEY (Producto_Id) REFERENCES Productos(Id_Producto), Cantidad INT NOT NULL, Fechahora DATETIME);

